
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.kdudek.rdl.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TRANSACTIONAL = 20;
  public static final int STRING_LITERAL = 39;
  public static final int LBRACKET = 27;
  public static final int PUT = 11;
  public static final int SECURE = 19;
  public static final int LPAREN = 25;
  public static final int JAVA_DOC = 37;
  public static final int STATUS = 18;
  public static final int DELETE = 12;
  public static final int RPAREN = 26;
  public static final int SEMICOLON = 33;
  public static final int LT = 29;
  public static final int COMMA = 31;
  public static final int GET = 9;
  public static final int PATCH = 13;
  public static final int TRAIT = 4;
  public static final int DOT = 34;
  public static final int EOF = 0;
  public static final int EQUAL = 36;
  public static final int RBRACKET = 28;
  public static final int error = 1;
  public static final int VOID = 21;
  public static final int RESOURCE = 5;
  public static final int HEAD = 14;
  public static final int IMPORT = 3;
  public static final int COLON = 32;
  public static final int LBRACE = 23;
  public static final int PATH_LITERAL = 38;
  public static final int POST = 10;
  public static final int PACKAGE = 2;
  public static final int RBRACE = 24;
  public static final int EXTENDS = 8;
  public static final int OVERRIDE = 7;
  public static final int QUESTION = 35;
  public static final int RETURNS = 17;
  public static final int USES = 6;
  public static final int AT = 22;
  public static final int GT = 30;
  public static final int EXPECTS = 16;
  public static final int OPTIONS = 15;
  public static final int INT_LITERAL = 41;
  public static final int IDENTIFIER = 40;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PACKAGE",
  "IMPORT",
  "TRAIT",
  "RESOURCE",
  "USES",
  "OVERRIDE",
  "EXTENDS",
  "GET",
  "POST",
  "PUT",
  "DELETE",
  "PATCH",
  "HEAD",
  "OPTIONS",
  "EXPECTS",
  "RETURNS",
  "STATUS",
  "SECURE",
  "TRANSACTIONAL",
  "VOID",
  "AT",
  "LBRACE",
  "RBRACE",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "LT",
  "GT",
  "COMMA",
  "COLON",
  "SEMICOLON",
  "DOT",
  "QUESTION",
  "EQUAL",
  "JAVA_DOC",
  "PATH_LITERAL",
  "STRING_LITERAL",
  "IDENTIFIER",
  "INT_LITERAL"
  };
}

