// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/flex/RdlLexer.flex

package com.kdudek.rdl.lexer;

import java.util.HashMap;
import java.util.Map;
import java_cup.runtime.Symbol;
import com.kdudek.rdl.parser.sym;


@SuppressWarnings("fallthrough")
public class lexer implements com.kdudek.rdl.parser.sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int LINE_COMMENT = 2;
  public static final int BLOCK_COMMENT = 4;
  public static final int DOC_COMMENT = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  1,  2,  2,  3,  3,  4, 4
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\0\1\6\1\7\1\10\3\0\1\11\1\12\1\13"+
    "\1\0\1\14\1\0\1\15\1\16\12\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\30\1\34\1\35\1\36\2\30\1\37"+
    "\1\30\1\40\1\41\1\42\2\30\1\43\1\44\1\45"+
    "\5\30\1\46\1\47\1\50\1\0\1\30\1\0\1\51"+
    "\1\30\1\52\1\53\1\54\1\30\1\55\1\30\1\56"+
    "\1\30\1\57\1\60\1\61\1\62\1\63\1\64\1\30"+
    "\1\65\1\66\1\67\1\70\1\71\1\30\1\72\2\30"+
    "\1\73\1\0\1\74\7\0\1\3\u01a2\0\2\3\326\0"+
    "\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\1\1\1\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\1\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\6\17\1\20\1\21\11\17\1\22\1\23\1\2"+
    "\1\1\1\2\2\24\3\2\4\25\1\0\1\26\2\0"+
    "\1\27\1\30\21\17\2\0\1\31\1\32\1\33\1\34"+
    "\1\35\1\0\1\36\1\17\1\37\4\17\1\40\14\17"+
    "\1\0\1\17\1\41\2\17\1\42\13\17\1\43\1\44"+
    "\1\0\2\17\1\45\11\17\1\46\1\17\1\0\1\47"+
    "\3\17\1\50\4\17\1\51\1\52\1\17\1\0\1\53"+
    "\1\54\1\55\1\17\1\56\1\17\1\57\1\17\1\0"+
    "\1\60\1\61\1\17\1\0\1\17\1\62\1\0\3\17"+
    "\1\63";

  private static int [] zzUnpackAction() {
    int [] result = new int[171];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\75\0\172\0\267\0\364\0\u0131\0\u016e\0\u01ab"+
    "\0\u0131\0\u0131\0\u0131\0\u0131\0\u01e8\0\u0225\0\u0131\0\u0131"+
    "\0\u0131\0\u0131\0\u0131\0\u0131\0\u0131\0\u0262\0\u029f\0\u02dc"+
    "\0\u0319\0\u0356\0\u0393\0\u0131\0\u0131\0\u03d0\0\u040d\0\u044a"+
    "\0\u0487\0\u04c4\0\u0501\0\u053e\0\u057b\0\u05b8\0\u0131\0\u0131"+
    "\0\u05f5\0\u0632\0\u0131\0\u0131\0\u066f\0\u06ac\0\u06e9\0\u0726"+
    "\0\u0131\0\u0763\0\u07a0\0\u07dd\0\u081a\0\u0131\0\u0857\0\u0894"+
    "\0\u08d1\0\u0131\0\u090e\0\u094b\0\u0988\0\u09c5\0\u0a02\0\u0a3f"+
    "\0\u0a7c\0\u0ab9\0\u0af6\0\u0b33\0\u0b70\0\u0bad\0\u0bea\0\u0c27"+
    "\0\u0c64\0\u0ca1\0\u0cde\0\u0632\0\u0d1b\0\u0131\0\u0131\0\u0131"+
    "\0\u0131\0\u0131\0\u0d58\0\u0131\0\u0d95\0\u0262\0\u0dd2\0\u0e0f"+
    "\0\u0e4c\0\u0e89\0\u0262\0\u0ec6\0\u0f03\0\u0f40\0\u0f7d\0\u0fba"+
    "\0\u0ff7\0\u1034\0\u1071\0\u10ae\0\u10eb\0\u1128\0\u1165\0\u11a2"+
    "\0\u11df\0\u0262\0\u121c\0\u1259\0\u0262\0\u1296\0\u12d3\0\u1310"+
    "\0\u134d\0\u138a\0\u13c7\0\u1404\0\u1441\0\u147e\0\u14bb\0\u14f8"+
    "\0\u0262\0\u0262\0\u1535\0\u1572\0\u15af\0\u0262\0\u15ec\0\u1629"+
    "\0\u1666\0\u16a3\0\u16e0\0\u171d\0\u175a\0\u1797\0\u17d4\0\u0262"+
    "\0\u1811\0\u184e\0\u0262\0\u188b\0\u18c8\0\u1905\0\u0262\0\u1942"+
    "\0\u197f\0\u19bc\0\u19f9\0\u0262\0\u0262\0\u1a36\0\u1a73\0\u0262"+
    "\0\u0262\0\u0262\0\u1ab0\0\u0262\0\u1aed\0\u0262\0\u1b2a\0\u1b67"+
    "\0\u0262\0\u0262\0\u1ba4\0\u1be1\0\u1c1e\0\u0131\0\u1c5b\0\u1c98"+
    "\0\u1cd5\0\u1d12\0\u0262";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[171];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\6\2\7\1\0\2\7\1\10\2\6\1\11\1\12"+
    "\1\6\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\3\26\1\27\1\26\1\30"+
    "\1\31\3\26\1\32\1\33\3\26\1\34\1\6\1\35"+
    "\3\26\1\36\1\26\1\37\4\26\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\26\1\47\1\50\1\6"+
    "\2\51\1\0\2\51\1\10\1\52\1\6\1\11\1\12"+
    "\1\6\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\3\26\1\27\1\26\1\30"+
    "\1\31\3\26\1\32\1\33\3\26\1\34\1\6\1\35"+
    "\3\26\1\36\1\26\1\37\4\26\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\26\1\47\1\50\2\53"+
    "\1\54\2\0\1\55\72\53\2\0\1\56\5\53\1\57"+
    "\2\53\1\60\56\53\3\61\2\0\1\62\5\61\1\63"+
    "\2\61\1\64\56\61\76\0\2\7\1\0\2\7\67\0"+
    "\2\65\1\0\2\65\1\0\1\66\7\65\1\67\30\65"+
    "\1\70\25\65\13\0\1\71\2\0\1\72\75\0\1\16"+
    "\74\0\1\26\7\0\17\26\3\0\22\26\21\0\1\26"+
    "\7\0\4\26\1\73\12\26\3\0\22\26\21\0\1\26"+
    "\7\0\4\26\1\74\12\26\3\0\22\26\21\0\1\26"+
    "\7\0\4\26\1\75\12\26\3\0\22\26\21\0\1\26"+
    "\7\0\13\26\1\76\3\26\3\0\22\26\21\0\1\26"+
    "\7\0\1\77\11\26\1\100\3\26\1\101\3\0\22\26"+
    "\21\0\1\26\7\0\17\26\3\0\21\26\1\102\21\0"+
    "\1\26\7\0\17\26\3\0\10\26\1\103\11\26\21\0"+
    "\1\26\7\0\17\26\3\0\20\26\1\104\1\26\21\0"+
    "\1\26\7\0\17\26\3\0\1\105\21\26\21\0\1\26"+
    "\7\0\17\26\3\0\3\26\1\106\16\26\21\0\1\26"+
    "\7\0\17\26\3\0\3\26\1\107\12\26\1\110\3\26"+
    "\21\0\1\26\7\0\17\26\3\0\14\26\1\111\5\26"+
    "\21\0\1\26\7\0\17\26\3\0\15\26\1\112\4\26"+
    "\21\0\1\26\7\0\17\26\3\0\12\26\1\113\7\26"+
    "\3\0\2\51\1\0\2\51\1\0\1\114\156\0\1\115"+
    "\5\0\1\54\74\0\1\53\110\0\1\116\71\0\1\117"+
    "\63\0\1\61\110\0\1\120\71\0\1\121\61\0\2\65"+
    "\1\0\2\65\1\0\1\66\40\65\1\70\25\65\2\67"+
    "\1\0\2\67\1\0\1\122\40\67\1\123\25\67\6\0"+
    "\1\65\1\0\1\65\36\0\1\65\12\0\1\65\2\0"+
    "\1\65\1\0\1\65\3\0\2\65\13\0\1\124\100\0"+
    "\1\26\7\0\10\26\1\125\6\26\3\0\22\26\21\0"+
    "\1\26\7\0\15\26\1\126\1\26\3\0\22\26\21\0"+
    "\1\26\7\0\1\127\16\26\3\0\22\26\21\0\1\26"+
    "\7\0\15\26\1\130\1\26\3\0\22\26\21\0\1\26"+
    "\7\0\15\26\1\131\1\26\3\0\22\26\21\0\1\26"+
    "\7\0\14\26\1\132\2\26\3\0\22\26\21\0\1\26"+
    "\7\0\15\26\1\133\1\26\3\0\22\26\21\0\1\26"+
    "\7\0\17\26\3\0\13\26\1\134\2\26\1\135\3\26"+
    "\21\0\1\26\7\0\17\26\3\0\13\26\1\136\6\26"+
    "\21\0\1\26\7\0\17\26\3\0\3\26\1\137\16\26"+
    "\21\0\1\26\7\0\17\26\3\0\1\26\1\140\20\26"+
    "\21\0\1\26\7\0\17\26\3\0\15\26\1\141\1\142"+
    "\3\26\21\0\1\26\7\0\17\26\3\0\1\26\1\143"+
    "\20\26\21\0\1\26\7\0\17\26\3\0\1\144\21\26"+
    "\21\0\1\26\7\0\17\26\3\0\1\145\21\26\21\0"+
    "\1\26\7\0\17\26\3\0\3\26\1\146\16\26\21\0"+
    "\1\26\7\0\17\26\3\0\5\26\1\147\14\26\53\0"+
    "\1\150\31\0\1\67\1\0\1\67\36\0\1\67\12\0"+
    "\1\67\2\0\1\67\1\0\1\67\3\0\2\67\17\0"+
    "\1\26\7\0\4\26\1\151\12\26\3\0\22\26\21\0"+
    "\1\26\7\0\3\26\1\152\13\26\3\0\22\26\21\0"+
    "\1\26\7\0\7\26\1\153\7\26\3\0\22\26\21\0"+
    "\1\26\7\0\2\26\1\154\14\26\3\0\22\26\21\0"+
    "\1\26\7\0\15\26\1\155\1\26\3\0\22\26\21\0"+
    "\1\26\7\0\17\26\3\0\3\26\1\156\16\26\21\0"+
    "\1\26\7\0\17\26\3\0\3\26\1\157\16\26\21\0"+
    "\1\26\7\0\17\26\3\0\12\26\1\160\7\26\21\0"+
    "\1\26\7\0\17\26\3\0\14\26\1\161\5\26\21\0"+
    "\1\26\7\0\17\26\3\0\6\26\1\162\13\26\21\0"+
    "\1\26\7\0\17\26\3\0\12\26\1\163\7\26\21\0"+
    "\1\26\7\0\17\26\3\0\17\26\1\164\2\26\21\0"+
    "\1\26\7\0\17\26\3\0\17\26\1\165\2\26\21\0"+
    "\1\26\7\0\17\26\3\0\16\26\1\166\3\26\21\0"+
    "\1\26\7\0\17\26\3\0\5\26\1\167\3\26\1\170"+
    "\10\26\21\0\1\26\7\0\17\26\3\0\15\26\1\171"+
    "\4\26\21\0\1\26\7\0\17\26\3\0\2\26\1\172"+
    "\17\26\67\0\1\173\26\0\1\26\7\0\15\26\1\174"+
    "\1\26\3\0\22\26\21\0\1\26\7\0\12\26\1\175"+
    "\4\26\3\0\22\26\21\0\1\26\7\0\6\26\1\176"+
    "\10\26\3\0\22\26\21\0\1\26\7\0\17\26\3\0"+
    "\1\26\1\177\20\26\21\0\1\26\7\0\17\26\3\0"+
    "\11\26\1\200\10\26\21\0\1\26\7\0\17\26\3\0"+
    "\14\26\1\201\5\26\21\0\1\26\7\0\17\26\3\0"+
    "\14\26\1\202\5\26\21\0\1\26\7\0\17\26\3\0"+
    "\1\203\21\26\21\0\1\26\7\0\17\26\3\0\17\26"+
    "\1\204\2\26\21\0\1\26\7\0\17\26\3\0\14\26"+
    "\1\205\5\26\21\0\1\26\7\0\17\26\3\0\14\26"+
    "\1\206\5\26\21\0\1\26\7\0\17\26\3\0\17\26"+
    "\1\207\2\26\21\0\1\26\7\0\17\26\3\0\16\26"+
    "\1\210\3\26\21\0\1\26\7\0\17\26\3\0\15\26"+
    "\1\211\4\26\3\0\2\212\1\0\2\212\106\0\1\26"+
    "\7\0\4\26\1\213\12\26\3\0\22\26\21\0\1\26"+
    "\7\0\11\26\1\214\5\26\3\0\22\26\21\0\1\26"+
    "\7\0\17\26\3\0\16\26\1\215\3\26\21\0\1\26"+
    "\7\0\17\26\3\0\2\26\1\216\17\26\21\0\1\26"+
    "\7\0\17\26\3\0\16\26\1\217\3\26\21\0\1\26"+
    "\7\0\17\26\3\0\5\26\1\220\14\26\21\0\1\26"+
    "\7\0\17\26\3\0\4\26\1\221\15\26\21\0\1\26"+
    "\7\0\17\26\3\0\14\26\1\222\5\26\21\0\1\26"+
    "\7\0\17\26\3\0\11\26\1\223\10\26\21\0\1\26"+
    "\7\0\17\26\3\0\3\26\1\224\16\26\21\0\1\26"+
    "\7\0\17\26\3\0\15\26\1\225\4\26\21\0\1\26"+
    "\7\0\17\26\3\0\1\226\21\26\3\0\2\212\1\0"+
    "\2\212\21\0\17\227\3\0\22\227\21\0\1\26\7\0"+
    "\14\26\1\230\2\26\3\0\22\26\21\0\1\26\7\0"+
    "\17\26\3\0\15\26\1\231\4\26\21\0\1\26\7\0"+
    "\17\26\3\0\15\26\1\232\4\26\21\0\1\26\7\0"+
    "\17\26\3\0\2\26\1\233\17\26\21\0\1\26\7\0"+
    "\17\26\3\0\3\26\1\234\16\26\21\0\1\26\7\0"+
    "\17\26\3\0\1\26\1\235\20\26\21\0\1\26\7\0"+
    "\17\26\3\0\15\26\1\236\4\26\21\0\1\26\7\0"+
    "\17\26\3\0\1\26\1\237\20\26\3\0\2\240\1\0"+
    "\2\240\11\0\1\227\7\0\17\227\3\0\22\227\21\0"+
    "\1\26\7\0\17\26\3\0\3\26\1\241\16\26\21\0"+
    "\1\26\7\0\17\26\3\0\3\26\1\242\16\26\21\0"+
    "\1\26\7\0\17\26\3\0\16\26\1\243\3\26\3\0"+
    "\2\240\1\0\2\240\1\244\105\0\1\26\7\0\17\26"+
    "\3\0\5\26\1\245\14\26\2\0\2\244\1\0\2\244"+
    "\1\0\1\246\40\244\1\247\25\244\17\0\1\26\7\0"+
    "\17\26\3\0\12\26\1\250\7\26\10\0\1\244\1\0"+
    "\1\244\36\0\1\244\12\0\1\244\2\0\1\244\1\0"+
    "\1\244\3\0\2\244\17\0\1\26\7\0\17\26\3\0"+
    "\11\26\1\251\10\26\21\0\1\26\7\0\17\26\3\0"+
    "\1\252\21\26\21\0\1\26\7\0\17\26\3\0\7\26"+
    "\1\253\12\26\2\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[7503];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\5\0\1\11\2\1\4\11\2\1\7\11\6\1\2\11"+
    "\11\1\2\11\2\1\2\11\4\1\1\11\3\1\1\0"+
    "\1\11\2\0\1\1\1\11\21\1\2\0\5\11\1\0"+
    "\1\11\23\1\1\0\22\1\1\0\16\1\1\0\14\1"+
    "\1\0\10\1\1\0\3\1\1\0\1\1\1\11\1\0"+
    "\4\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[171];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private final Map<String, String> macros = new HashMap<>();
    private int blockDepth = 0;
    private StringBuilder docBuf;

    private Symbol sym(int id) {
        return new Symbol(id, yyline + 1, yycolumn + 1);
    }

    private Symbol sym(int id, Object v) {
        return new Symbol(id, yyline + 1, yycolumn + 1, v);
    }

    private String substitute(String txt) {
        StringBuilder out = new StringBuilder();
        int i = 0;
        while (i < txt.length()) {
            int open = txt.indexOf("${", i);
            if (open < 0) {
                out.append(txt.substring(i));
                break;
            }
            out.append(txt, i, open);
            int close = txt.indexOf('}', open + 2);
            if (close < 0)
                throw new RuntimeException("Unterminated ${  in line " + (yyline + 1));
            String key = txt.substring(open + 2, close);
            String val = macros.get(key);
            if (val == null)
                throw new RuntimeException("Undefined macro \"" + key + "\" in line " + (yyline + 1));
            out.append(val);
            i = close + 1;
        }
        return out.toString();
    }

    private String unescape(String raw) {
        StringBuilder b = new StringBuilder();
        for (int i = 0; i < raw.length(); i++) {
            char c = raw.charAt(i);
            if (c == '\\') {
                if (i == raw.length() - 1) throw new RuntimeException("Bad escape seq @ line " + (yyline + 1));
                char n = raw.charAt(++i);
                switch (n) {
                    case 'n':
                        b.append('\n');
                        break;
                    case 'r':
                        b.append('\r');
                        break;
                    case 't':
                        b.append('\t');
                        break;
                    case '"':
                        b.append('\"');
                        break;
                    case '\\':
                        b.append('\\');
                        break;
                    case '{':
                        b.append('{');
                        break;
                    case '}':
                        b.append('}');
                        break;
                    case '$':
                        b.append('$');
                        break;
                    default:
                        b.append(n);
                        break;
                }
            } else b.append(c);
        }
        return b.toString();
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      if (zzMarkedPosL > zzStartRead) {
        switch (zzBufferL[zzMarkedPosL-1]) {
        case '\n':
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':  // fall through
          zzAtBOL = true;
          break;
        case '\r': 
          if (zzMarkedPosL < zzEndReadL)
            zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          else if (zzAtEOF)
            zzAtBOL = false;
          else {
            boolean eof = zzRefill();
            zzMarkedPosL = zzMarkedPos;
            zzEndReadL = zzEndRead;
            zzBufferL = zzBuffer;
            if (eof) 
              zzAtBOL = false;
            else 
              zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          }
          break;
        default:
          zzAtBOL = false;
        }
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      if (zzAtBOL)
        zzState = ZZ_LEXSTATE[zzLexicalState+1];
      else
        zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case LINE_COMMENT: {
              yybegin(YYINITIAL);
            }  // fall though
            case 172: break;
            case BLOCK_COMMENT: {
              throw new RuntimeException("Unterminated block comment (/*) at EOF");
            }  // fall though
            case 173: break;
            case DOC_COMMENT: {
              throw new RuntimeException("Unterminated doc comment (/**) at EOF");
            }  // fall though
            case 174: break;
            default:
          { return new java_cup.runtime.Symbol(sym.EOF); }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new RuntimeException(
        "Lexical error: illegal char '" + yytext() +
        "' at line " + (yyline+1) + ", column " + (yycolumn+1));
            }
          // fall through
          case 52: break;
          case 2:
            { /* skip */
            }
          // fall through
          case 53: break;
          case 3:
            { return sym(LPAREN);
            }
          // fall through
          case 54: break;
          case 4:
            { return sym(RPAREN);
            }
          // fall through
          case 55: break;
          case 5:
            { return sym(COMMA);
            }
          // fall through
          case 56: break;
          case 6:
            { return sym(DOT);
            }
          // fall through
          case 57: break;
          case 7:
            { return sym(INT_LITERAL, Integer.valueOf(yytext()));
            }
          // fall through
          case 58: break;
          case 8:
            { return sym(COLON);
            }
          // fall through
          case 59: break;
          case 9:
            { return sym(SEMICOLON);
            }
          // fall through
          case 60: break;
          case 10:
            { return sym(LT);
            }
          // fall through
          case 61: break;
          case 11:
            { return sym(EQUAL);
            }
          // fall through
          case 62: break;
          case 12:
            { return sym(GT);
            }
          // fall through
          case 63: break;
          case 13:
            { return sym(QUESTION);
            }
          // fall through
          case 64: break;
          case 14:
            { return sym(AT);
            }
          // fall through
          case 65: break;
          case 15:
            { return sym(IDENTIFIER, yytext());
            }
          // fall through
          case 66: break;
          case 16:
            { return sym(LBRACKET);
            }
          // fall through
          case 67: break;
          case 17:
            { return sym(RBRACKET);
            }
          // fall through
          case 68: break;
          case 18:
            { return sym(LBRACE);
            }
          // fall through
          case 69: break;
          case 19:
            { return sym(RBRACE);
            }
          // fall through
          case 70: break;
          case 20:
            { yybegin(YYINITIAL);
            }
          // fall through
          case 71: break;
          case 21:
            { docBuf.append(yytext());
            }
          // fall through
          case 72: break;
          case 22:
            { String raw = yytext();
                        String val = substitute(unescape(raw.substring(1, raw.length()-1)));
                        return sym(STRING_LITERAL, val);
            }
          // fall through
          case 73: break;
          case 23:
            { blockDepth = 1; yybegin(BLOCK_COMMENT);
            }
          // fall through
          case 74: break;
          case 24:
            { yybegin(LINE_COMMENT);
            }
          // fall through
          case 75: break;
          case 25:
            { blockDepth--;
                        if (blockDepth == 0) yybegin(YYINITIAL);
            }
          // fall through
          case 76: break;
          case 26:
            { blockDepth++;
            }
          // fall through
          case 77: break;
          case 27:
            { blockDepth--;
                        if (blockDepth == 0) {
                            String text = docBuf.toString();
                            yybegin(YYINITIAL);
                            return sym(JAVA_DOC, text);
                        } else docBuf.append("*/");
            }
          // fall through
          case 78: break;
          case 28:
            { blockDepth++; docBuf.append("/*");
            }
          // fall through
          case 79: break;
          case 29:
            { String raw = yytext();
                        String val = substitute(unescape(raw.substring(1, raw.length()-1)));
                        return sym(PATH_LITERAL, val);
            }
          // fall through
          case 80: break;
          case 30:
            { docBuf = new StringBuilder(); blockDepth = 1; yybegin(DOC_COMMENT);
            }
          // fall through
          case 81: break;
          case 31:
            { return sym(GET);
            }
          // fall through
          case 82: break;
          case 32:
            { return sym(PUT);
            }
          // fall through
          case 83: break;
          case 33:
            { return sym(HEAD);
            }
          // fall through
          case 84: break;
          case 34:
            { return sym(POST);
            }
          // fall through
          case 85: break;
          case 35:
            { return sym(USES);
            }
          // fall through
          case 86: break;
          case 36:
            { return sym(VOID);
            }
          // fall through
          case 87: break;
          case 37:
            { return sym(PATCH);
            }
          // fall through
          case 88: break;
          case 38:
            { return sym(TRAIT);
            }
          // fall through
          case 89: break;
          case 39:
            { return sym(DELETE);
            }
          // fall through
          case 90: break;
          case 40:
            { return sym(IMPORT);
            }
          // fall through
          case 91: break;
          case 41:
            { return sym(SECURE);
            }
          // fall through
          case 92: break;
          case 42:
            { return sym(STATUS);
            }
          // fall through
          case 93: break;
          case 43:
            { return sym(OPTIONS);
            }
          // fall through
          case 94: break;
          case 44:
            { return sym(EXPECTS);
            }
          // fall through
          case 95: break;
          case 45:
            { return sym(EXTENDS);
            }
          // fall through
          case 96: break;
          case 46:
            { return sym(PACKAGE);
            }
          // fall through
          case 97: break;
          case 47:
            { return sym(RETURNS);
            }
          // fall through
          case 98: break;
          case 48:
            { return sym(OVERRIDE);
            }
          // fall through
          case 99: break;
          case 49:
            { return sym(RESOURCE);
            }
          // fall through
          case 100: break;
          case 50:
            { String[] parts = yytext().trim().split("\\s+", 4);
          String name= parts[1];
          String rawVal = parts[2];
          String val = unescape(rawVal.substring(1, rawVal.length()-1));
          macros.put(name, val);
            }
          // fall through
          case 101: break;
          case 51:
            { return sym(TRANSACTIONAL);
            }
          // fall through
          case 102: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
